modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "reeses_sodium_options"

version = "${version}"
displayName = "Reese's Sodium Options"

logoFile = "assets/reeses-sodium-options/icon.png" #optional

authors = "FlashyReese"

description = '''
Replaces Sodium's Options Screen
'''

[[dependencies.reeses_sodium_options]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.0,26.2.0)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reeses_sodium_options]]
modId = "sodium"
type = "required"
versionRange = "[0.9.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.reeses_sodium_options]]
modId = "controlify"
type = "optional"
versionRange = "[3.0.2,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "reeses-sodium-options.mixins.json"

[modproperties.reeses_sodium_options]
"sodium:config_api_user" = "me.flashyreese.mods.reeses_sodium_options.client.config.ReeseSodiumOptionsConfigEntryPoint"
