name: Java CI with Gradle

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build Artifacts - Fabric
        uses: actions/upload-artifact@v7
        with:
          name: 'RSO Fabric Artifacts'
          path: fabric/build/libs
      - name: Upload Build Artifacts - NeoForge
        uses: actions/upload-artifact@v7
        with:
          name: 'RSO NeoForge Artifacts'
          path: neoforge/build/libs
