name: Self-Hosted runner CI with Gradle

on: [push]

jobs:
  selfhost-build:
    if: github.repository_owner == 'FlashyReese'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          check-latest: true
      - name: Build and Publish with Gradle
        run: ./gradlew build publishAllPublicationsToFlashyReeseSnapshotsRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload Build Artifacts - Fabric
        uses: actions/upload-artifact@v7
        with:
          name: 'RSO Fabric Artifacts'
          path: fabric/build/libs
      - name: Upload Build Artifacts - NeoForge
        uses: actions/upload-artifact@v7
        with:
          name: 'RSO NeoForge Artifacts'
          path: neoforge/build/libs
